### Crear un nuevo ticket (POST)

POST http://localhost:5000/tickets
Content-Type: application/json

{
  "asunto": "Sistema abajo",
  "descripcion": "El sistema está abajo actualmente.",
  "prioridad": "Alta",
  "estado": "Abierto",
  "usuario_id": 10,
  "tecnico_id": 3
}


