### Editar un ticket (POST)

# Simular POST con nuevos datos del ticket

PUT http://localhost:5000/tickets/7
Content-Type: application/json

{
  "asunto": "Error corregido en servidor",
  "descripcion": "El sistema fue actualizado y ahora funciona correctamente",
  "prioridad": "Media",
  "estado": "En proceso"
}

